### ISSUE TITLE
Add LLM connector for Amazon Bedrock API

### ISSUE THREAD

**Issue by rgriff23** [BCG-X-Official/artkit#18]
## Justification

[Amazon Bedrock](https://aws.amazon.com/bedrock/) provides an extensive suite of Gen AI models via a single API. Supporting Amazon Bedrock will significantly enhance ARTKIT's versatility.

## Details

Note that the Bedrock API supports multiple modalities, depending on the selected model. This issue is for LLMs. The new class will live in `src/artkit/model/llm/aws/`

Be sure to update the docs:

- `README`: https://github.com/BCG-X-Official/artkit?tab=readme-ov-file#supported-model-providers
- `Contributing`: https://github.com/BCG-X-Official/artkit/blob/1.0.x/sphinx/source/user_guide/introduction_to_artkit/connecting_to_genai_models.ipynb
- `Connecting to Gen AI Models`: https://github.com/BCG-X-Official/artkit/blob/1.0.x/sphinx/source/user_guide/introduction_to_artkit/connecting_to_genai_models.ipynb
- `.env_example`: https://github.com/BCG-X-Official/artkit/blob/1.0.x/.env_example

Please see the tutorial: [Creating New Model Classes](https://bcg-x-official.github.io/artkit/user_guide/advanced_tutorials/creating_custom_model_classes.html)

**Comment by matthew-wong-bcg** [comment]
PR Merged and slated for the next release
