### ISSUE TITLE
Add connector to Vertex AI API models

### ISSUE THREAD

**Issue by patilpriyadarshini** [BCG-X-Official/artkit#59]
Please can you provide few documentation regarding the same and the gemini url that is being used.

**Comment by seanggani** [comment]
Hi @patilpriyadarshini, thank you for raising this issue! We are working on this right now and will keep you updated. Let's use this ticket as the source of truth and I will close this other [issue](https://github.com/BCG-X-Official/artkit/issues/58) as it is a duplicate

**Comment by seanggani** [comment]
@patilpriyadarshini you can find the instructions to connect to Google Gemin in this link: https://github.com/BCG-X-Official/artkit/blob/1.0.x/sphinx/source/user_guide/introduction_to_artkit/connecting_to_genai_models.ipynb. 
We will deploy the updated docs to include these changes by the end of this week, please let us know if this resolves your issue!


![Screenshot 2024-07-29 at 4 29 01 PM](https://github.com/user-attachments/assets/c5e75f51-f77c-422c-84fe-dacf47e2b423)

**Comment by patilpriyadarshini** [comment]
Can we connect to GeminiChat using Vertex AI API? @seanggani

**Comment by seanggani** [comment]
@patilpriyadarshini unfortunately we don't have a direct integration with the Vertex AI API yet, but could you please elaborate what functionality you want to use in GeminiChat that is not supported using the ARTKIT wrapper? Thank you!

**Comment by patilpriyadarshini** [comment]
In current case GeminiChat uses GenerativeModel from google.generativeai which is general model for all generative AI tasks so there is huge difference between the response of LLM from google.generativeai as compared with vertexai.generative_models. So wanted to check if artkit provides any direct integration with Vertex AI API.

**Comment by seanggani** [comment]
I see, thank you for the details! @patilpriyadarshini at this moment ARTKIT doesn't have integration with the Vertex AI API, so here's what I recommend:

let's rename this issue to be an enhancement "Add connector to Vertex AI API models".I will discuss with the team and update this issue if/when we create this connector. We also highly encourage contributors to contribute in our open source repository!

**Comment by seanggani** [comment]
@patilpriyadarshini I am actively working on a Vertex AI API connector now, can you please confirm if this vertex AI generative_models is the most helpful for you? Please let me know if there are other packages such as `language_models` that would be helpful. Thank you! https://cloud.google.com/vertex-ai/generative-ai/docs/reference/python/latest/vertexai.generative_models

**Comment by patilpriyadarshini** [comment]
@seanggani Thank you for taking up this as an enhancement. Yes the vertex AI connection would be really helpful because the response from these models is more promising when tested.

**Comment by seanggani** [comment]
@patilpriyadarshini Can you please review this [PR](https://github.com/BCG-X-Official/artkit/pull/62) and check if this works for your use case? Thank you!

**Comment by seanggani** [comment]
The latest Vertex AI integration has been released with ARTKIT 1.0.7, so I'm closing this issue
